[profile.default]
src = "src"
out = "out"
libs = ["lib"]
show_progress = true
names = true

[fmt]
line_length = 80
single_line_statement_blocks = "multi"
multiline_func_header = "all"

[invariant]
runs = 100000
depth = 25
fail_on_revert = true
corpus_dir = "corpus"
show_edge_coverage = true
show_metrics = true
show_solidity = true

[lint]
exclude_lints = [
  "mixed-case-variable",
  "mixed-case-function",
  "screaming-snake-case-const",
  "screaming-snake-case-immutable",
]
