[package]
name = "zk"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "spec_mismatch"
path = "src/spec_mismatch/bin/main.rs"

[dependencies]
risc0-steel = { features = ["host"], git = "https://github.com/risc0/risc0-ethereum", tag = "v2.2.0" }

