[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "eth-account>=0.13.7",
    "eth-utils>=5.3.0",
    "requests>=2.32.4",
]
